//The sequence of triangle numbers is generated by adding the natural numbers.
//So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

//What is the value of the first triangle number to have over five hundred divisors?

public static void main(String[] args) {
    int triangle = 0;
    int n = 2;
    for (int i = 1; i < n; i++) {
        triangle += i;
        if (findDivisors(triangle) < 500) n++;
    }
    System.out.println(triangle);
}

public static int findDivisors(int num) {
    int divisors = 0;
    for (int i = 1; i*i < num; i++) {
        if (num%i == 0) {
            if (i*i == num) divisors++;
            else divisors += 2;
        }
    }
    return divisors;
}